version: '3.9'

volumes:
  mysql_data:
    driver: local

services:
  studyloft-mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DevS3cret
      - MYSQL_PASSWORD=DevAn0thrS3crt
      - MYSQL_USER=studyloft_api_db_user
      - MYSQL_DATABASE=studyloft_api_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  studyloft_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=local
    image: studyloft_api:latest
    ports:
      - "8091:8091"
    depends_on:
      studyloft-mysql:
        condition: service_healthy